"""Sheet constants."""

# Names of columns in the DescriptorSheet.
COLUMNS = [
    'Sample name',
    'collection name',
    'experimental design',
    'Scientist',
    'PI',
    'Method',
    'Protocol document',
    'Protein',
    'cells/tissue',
    'condition (optional)',
    'mapto',
    "5' barcode",
    "3' adapter",
    'sequencer type',
    'antibody used',
    'RT primer',
    'linker',
    'consensus mapping (optional)',
    'PMID of published data (optional)',
    'data link (optional)',
    'year of data release (optional)',
    'MW band cut (kDa) (optional)',
    'replicate (optional)',
    'sequencing length (optional)',
    'resequencing ID (optional)',
    'page of gel images in lab notebook (optional)',
    'date of gel images in lab notebook (optional)',
    'comments (optional)',
]

REQUIRED_COLUMNS = [
    "Sample name",
    "collection name",
    "experimental design",
    "Scientist",
    "PI",
    "Method",
    'Protocol document',
    'Protein',
    'cells/tissue',
    'mapto',
    "5' barcode",
    "3' adapter",
    'sequencer type',
    'antibody used',
    'RT primer',
    'linker',
]

# Maximal accepted lenth of sample name.
MAX_SAMPLE_NAME_SIZE = 99

# Name of the 5' barcode column
BARCODE5_COLUMN_NAME = "5' barcode"

# Name of the 3' barcode column
BARCODE3_COLUMN_NAME = "linker"

# Name of the Illumina adapter column
ADAPTER_COLUMN_NAME = "3' adapter"


# Set of allowed methods.
METHODS = {
    '4SU-iCLIP',
    'BrdU-CLIP',
    'CLAP', 'CLIP',
    'CLIP-seq',
    'FAST-iCLIP',
    'FLASH',
    'HITS-CLIP',
    'PAR-CLIP',
    'RIP',
    'eCLIP',
    'hiCLIP',
    'iCLIP',
    'irCLIP',
    'miCLIP',
    'sCLIP',
    'uvCLAP',
}

# Set of allowed proteins.
PROTEINS = {
    '53BP1',
    'AGO1',
    'GR100',
    'IgG',
    'OdTcapture',
    'PR100',
    'TIRR',
    'bisox',
    'ctrl',
    'input',
    'm1A',
    'm1G',
    'm2A',
    'm22G',
    'm3U',
    'm4C',
    'm62A',
    'm6A',
    'm8A',
    'noIgG',
    'noUV',
    'pA',
    'pG',
    'pseudoU',
    'sDMA',
    'temp',
}

# Set of allowed tissues.
TISSUES = {
    '293Flp',
    '3T3',
    '786O',
    'A375',
    'AF9',
    'BJAB',
    'BMDM',
    'Bcells',
    'CD4 T cells',
    'CD8 T cells',
    'CD8 Tcells',
    'CEM-SS',
    'CEM_SS',
    'CHP-212',
    'COS7',
    'Cal51',
    'DoHH2',
    'E.coli',
    'ESC',
    'ESC neurons',
    'Embryonic body',
    'H1',
    'H1299',
    'HAP1',
    'HCT116',
    'HEK293',
    'HEK293 HR1',
    'HEK293T',
    'HIV IIIB',
    'HUVEC',
    'Head',
    'Hela',
    'Hela nuclear extract',
    'HelaFlp',
    'HepG2',
    'Huh7.5',
    'IMR-32',
    'Jurkat',
    'K562',
    'MCF7',
    'MDA231',
    'MEF',
    'MOLM13',
    'Mutu',
    'N2A',
    'NSC',
    'NSC34',
    'OC13',
    'OCI-AML3',
    'P19',
    'PANC-1',
    'Raji',
    'S.aureus',
    'SHSY5Y',
    'SK-N-AS',
    'SKmel10',
    'SK1 yeast',
    'SMI',
    'TCMK',
    'THP-1',
    'U251',
    'U266',
    'U2932',
    'U2OS',
    'Usti_filaments',
    'Ustilago filaments',
    'WM164',
    'astrocytes',
    'brain',
    'brainstem',
    'cerebellum',
    'cortex',
    'dermal fibroblasts',
    'drosophila',
    'fission yeast',
    'frontal cortex',
    'hippocampus',
    'iPSC',
    'iPSC NPC',
    'iPSC motor neurons',
    'input',
    'motor neurons',
    'mushroom bodies',
    'myoblast',
    'neurons',
    'olfactory bulb',
    'oligo',
    'primary AML',
    'primary neurons',
    'rhabdomyosarcoma',
    'spinal cord',
    'striatum-thalamus',
    'temp',
    'temporal cortex',
    'yeast',
}
